TRI_LAYER_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
# WPM_ENABLE = yes  # Enable word per minute counter
# LTO_ENABLE = yes  # Makes hex file smaller at cost of compile time
OLED_ENABLE = yes
RGBLIGHT_ENABLE = no # to reduce firmware size
# UNICODE_ENABLE = yes
UNICODEMAP_ENABLE = yes
